# Generated by Django 3.2.3 on 2021-06-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authorreg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('con_password', models.CharField(max_length=255)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'authority_register',
            },
        ),
    ]
