# Generated by Django 3.2.3 on 2021-07-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addstupage',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Student_Id', models.CharField(max_length=255, unique=True)),
                ('First_Name', models.CharField(max_length=255)),
                ('Last_Name', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255, unique=True)),
                ('Mobile_Number', models.IntegerField()),
                ('Registration_Date', models.CharField(max_length=255)),
                ('Batch_No', models.CharField(max_length=255)),
                ('Departments', models.CharField(max_length=255)),
                ('Gender', models.CharField(max_length=255)),
                ('Blood_Group', models.CharField(max_length=255)),
                ('Parents_Name', models.CharField(max_length=255)),
                ('Parents_Mbl_Num', models.IntegerField()),
                ('Upload_Image', models.ImageField(upload_to='')),
                ('Address', models.CharField(max_length=500)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Time', models.TimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Addstu_page',
            },
        ),
        migrations.CreateModel(
            name='AddTeacherpage',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Teacher_Id', models.CharField(max_length=255, unique=True)),
                ('First_Name', models.CharField(max_length=255)),
                ('Last_Name', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255, unique=True)),
                ('Mobile_Number', models.IntegerField()),
                ('Joining_Date', models.CharField(max_length=255)),
                ('Nid_NO', models.IntegerField(unique=True)),
                ('Departments', models.CharField(max_length=255)),
                ('Gender', models.CharField(max_length=255)),
                ('Blood_Group', models.CharField(max_length=255)),
                ('Parents_Name', models.CharField(max_length=255)),
                ('Parents_Mbl_Num', models.IntegerField()),
                ('Upload_Image', models.ImageField(upload_to='')),
                ('Address', models.CharField(max_length=500)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Time', models.TimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'AddTeacherpage',
            },
        ),
        migrations.CreateModel(
            name='Authorregiss',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Fname', models.CharField(max_length=255)),
                ('Lname', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255, unique=True)),
                ('Phone_number', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=255)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Time', models.TimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'authority_reg',
            },
        ),
        migrations.CreateModel(
            name='Online_Apply',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Surname', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255, unique=True)),
                ('Phone_Number', models.IntegerField()),
                ('Gender', models.CharField(max_length=255)),
                ('Departments', models.CharField(max_length=255)),
                ('Guardian_Name', models.CharField(max_length=255)),
                ('Guardian_Number', models.CharField(max_length=255)),
                ('Personal_Identity', models.IntegerField(unique=True)),
                ('Img', models.ImageField(upload_to='')),
                ('Address', models.CharField(max_length=255)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Time', models.TimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Online_Apply_table',
            },
        ),
        migrations.CreateModel(
            name='Studentregi',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Student_Id', models.CharField(max_length=255, unique=True)),
                ('Fname', models.CharField(max_length=255)),
                ('Lname', models.CharField(max_length=255)),
                ('Depart', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255, unique=True)),
                ('Phone_number', models.IntegerField()),
                ('Password', models.CharField(max_length=255)),
                ('Check', models.CharField(max_length=255)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Time', models.TimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Student_reg',
            },
        ),
        migrations.CreateModel(
            name='Teacherreg',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Teacher_Id', models.CharField(max_length=255, unique=True)),
                ('Fname', models.CharField(max_length=255)),
                ('Lname', models.CharField(max_length=255)),
                ('Depart', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255, unique=True)),
                ('Phone_number', models.IntegerField()),
                ('Password', models.CharField(max_length=255)),
                ('Check', models.CharField(max_length=255)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Time', models.TimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Teacher_reg',
            },
        ),
        migrations.DeleteModel(
            name='Authorreg',
        ),
    ]
