# Generated by Django 3.2.3 on 2021-07-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0002_auto_20210727_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='addstupage',
            name='Trimester',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
