# Generated by Django 3.2.3 on 2021-07-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0003_addstupage_trimester'),
    ]

    operations = [
        migrations.AddField(
            model_name='online_apply',
            name='Trimester',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
