# Generated by Django 3.2.3 on 2021-07-31 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0005_addcourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddstuResult',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('First_name', models.CharField(max_length=255)),
                ('Last_name', models.CharField(max_length=255)),
                ('Batch_No', models.CharField(max_length=255)),
                ('Trimester', models.CharField(max_length=255)),
                ('Departments', models.CharField(max_length=255)),
                ('CGPA', models.CharField(max_length=255)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Time', models.TimeField(auto_now_add=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentApp.addstupage')),
            ],
            options={
                'db_table': 'AddStudentResults',
            },
        ),
    ]
